// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0Z0OKd0vm6W2UGuRvZgtpP0r2VrZv2Q',
    appId: '1:793621859017:android:61b64d8c4b94e386bb1b18',
    messagingSenderId: '793621859017',
    projectId: 'grocery-e4d8c',
    storageBucket: 'grocery-e4d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA53Z6XhFyV0zn0vnD2fhraEiPNumz-wbo',
    appId: '1:793621859017:ios:83020c5f56d9d423bb1b18',
    messagingSenderId: '793621859017',
    projectId: 'grocery-e4d8c',
    storageBucket: 'grocery-e4d8c.appspot.com',
    androidClientId: '793621859017-p9esiug82rmqp467onfst41upnhpbjia.apps.googleusercontent.com',
    iosClientId: '793621859017-djoi38959if54qshbjvcj5299ejc77pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );

}